export { default as Header } from "./Header/Header";
export { default as FlipCard } from "./FlipCard/FlipCard";
export { default as Categories } from "./Categories/Categories";
export { default as StartQuiz } from "./StartQuiz/StartQuiz";
export { default as Quiz } from "./Quiz/Quiz";
export { default as QuestionForm } from "./QuestionForm/QuestionForm";
export { default as About } from "./About/about";
export { default as Contact } from "./Contact/contact";
export { default as Footer } from "./Footer/footer";
